DjangoPro/DjangoPro/urls.py
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('poruke.urls'))
]

DjangoPro/poruke/urls.py
from django.urls import path
from . import views

app_name = 'poruke'

urlpatterns = [
    path('', views.index, name='index'),
    path('articles/', views.articles, name='articles'),
    path('articles/<int:id>/', views.article, name='article'),
    path('article/edit/<int:id>/', views.edit, name='edit'),
    path('article/new/', views.new, name='new')
]

DjangoPro/poruke/models.py
from django.db import models
from django.contrib.auth.models import User


class Article(models.Model):
    title = models.CharField(max_length=200 , default = '')
    content = models.TextField()
    num_views = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)



    def __str__(self):
        return self.content

    def is_popular(self):
        return self.num_views > 5


class Comment(models.Model):
    content = models.CharField(max_length=200)
    num_views = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

    def __str__(self):
        return self.content

DjangoPro/poruke/forms.py
from django.forms import ModelForm, Form
import django.forms as f
from .models import Article


class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content']

DjangoPro/poruke/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from .models import Article
from .forms import ArticleForm


def index(req):
    if not req.user.is_authenticated:
        return render(req, 'index.html', {'page_title': 'Vezbe 13'})
    else:
        return redirect('poruke:articles')


@login_required
def articles(req):
    tmp = Article.objects.all()
    return render(req, 'articles.html', {'articles': tmp})


@login_required
def article(req, id):
    tmp = get_object_or_404(Article, id=id)
    return render(req, 'article.html', {'article': tmp, 'page_title': tmp.title})


@permission_required('poruke.change_article')
def edit(req, id):
    if req.method == 'POST':
        form = ArticleForm(req.POST)

        if form.is_valid():
            a = Article.objects.get(id=id)
            a.title = form.cleaned_data['title']
            a.content = form.cleaned_data['content']
            a.save()
            return redirect('poruke:articles')
        else:
            return render(req, 'edit.html', {'form': form, 'id': id})
    else:
        a = Article.objects.get(id=id)
        form = ArticleForm(instance=a)
        return render(req, 'edit.html', {'form': form, 'id': id})


@permission_required('poruke.add_article')
def new(req):
    if req.method == 'POST':
        form = ArticleForm(req.POST)

        if form.is_valid():
            a = Article(title=form.cleaned_data['title'], content=form.cleaned_data['content'])
            a.save()
            return redirect('poruke:articles')
        else:
            return render(req, 'new.html', {'form': form})
    else:
        form = ArticleForm()
        return render(req, 'new.html', {'form': form})

DjangoPro/poruke/templates/article.html
{% extends 'master.html' %}

{% block content %}

    <div class="card">
        <div class="card-header">
            <h1>
                {{ article.title }}
                {% if perms.demo_app.change_article %}
                    <a href="{% url 'poruke:edit' article.id %}">
                        <span class="badge badge-primary">Edit</span>
                    </a>
                {% endif %}
            </h1>
        </div>
        <div class="card-body">
            <blockquote class="blockquote mb-0">
                <p>{{ article.content }}</p>
                <footer class="blockquote-footer">
                    Author:
                    <cite title="Source Title">
                        {{ article.owner.username }}
                    </cite>
                </footer>
            </blockquote>
        </div>
    </div>

{% endblock %}

DjangoPro/poruke/templates/articles.html
{%  extends 'master.html' %}

{% block title %}
    Articles
{% endblock %}

{%  block content %}
    <div class="list-group">
        {% for article in articles %}
            <a class="list-group-item list-group-item-action" href="{% url 'poruke:article' article.id %}">
                {{ article.title }}
            </a>
        {% endfor %}
    </div>
{% endblock %}

DjangoPro/poruke/templates/edit.html
{% extends 'master.html' %}

{% block title %}
    Edit article
{% endblock %}

{% block content %}

    <form method="post" action="{% url 'poruke:edit' id %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.title.id_for_label }}">{{ form.title.label_tag }}</label>
            <input type="text" class="form-control" id="{{ form.title.id_for_label }}" name="{{ form.title.name }}" value="{{ form.title.value }}">
            {% if form.title.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.title.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.content.id_for_label }}">{{ form.content.label_tag }}</label>
            <textarea class="form-control" id="{{ form.content.id_for_label }}" name="{{ form.content.name }}" rows="5">{{ form.content.value }}</textarea>
            {% if form.content.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.content.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <input type="submit" class="btn btn-primary btn-lg" value="Save"/>
    </form>

{% endblock %}

DjangoPro/poruke/templates/index.html
{%  extends 'master.html' %}

{%  block content %}
    <p>You are not logged in.</p>
    <a href="{% url 'login'%}">Click here to login.</a>
{% endblock %}

DjangoPro/poruke/templates/new.html
{% extends 'master.html' %}

{% block title %}
    New article
{% endblock %}

{% block content %}

    <form method="post" action="{% url 'poruke:new' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.title.id_for_label }}">{{ form.title.label_tag }}</label>
            <input type="text" class="form-control" id="{{ form.title.id_for_label }}" name="{{ form.title.name }}">
            {% if form.title.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.title.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.content.id_for_label }}">{{ form.content.label_tag }}</label>
            <textarea class="form-control" id="{{ form.content.id_for_label }}" name="{{ form.content.name }}" rows="5"></textarea>
            {% if form.content.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.content.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <input type="submit" class="btn btn-primary btn-lg" value="Add"/>
    </form>

{% endblock %}

DjangoPro/templates/header.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'poruke:articles' %}">
        <img src="{% static 'img/rocket.png' %}" width="30" height="30" class="d-inline-block align-top" alt="logo"/>
        Vezbe 13
    </a>

    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            {% if not perms.demo_app.add_article %}
                <a class="nav-link disabled" href="{% url 'poruke:new' %}">New article</a>
            {% else %}
                <a class="nav-link" href="{% url 'poruke:new' %}">New article</a>
            {% endif %}
        </li>
    </ul>

    {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'logout' %}">Logout {{ user.get_username }}</a>
    {% endif %}

</nav>

DjangoPro/templates/master.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>
            {% block title %}
                {{ page_title|default:"Untitled Page" }}
            {% endblock title %}
        </title>

        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    </head>

    <body>

        {% include 'header.html' %}

        <div class="container" style="text-align: center; margin-top: 50px">
            {% block content %}
                <p>Placeholder text in base template. Replace with page content.</p>
            {% endblock content %}
        </div>

    </body>
</html>